package ie.gmit.sw.breaker;


/**
* ie/gmit/sw/breaker/CORBAVigenereBreakerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from VigenereBreaker.idl
* Saturday, December 12, 2015 5:03:44 PM GMT
*/

public abstract class CORBAVigenereBreakerPOA extends org.omg.PortableServer.Servant
 implements ie.gmit.sw.breaker.CORBAVigenereBreakerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("decrypt", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ie/gmit/sw/breaker/CORBAVigenereBreaker/decrypt
       {
         String cypherText = in.read_string ();
         int maxKeyLength = in.read_long ();
         String $result = null;
         $result = this.decrypt (cypherText, maxKeyLength);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ie/gmit/sw/breaker/CORBAVigenereBreaker:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public CORBAVigenereBreaker _this() 
  {
    return CORBAVigenereBreakerHelper.narrow(
    super._this_object());
  }

  public CORBAVigenereBreaker _this(org.omg.CORBA.ORB orb) 
  {
    return CORBAVigenereBreakerHelper.narrow(
    super._this_object(orb));
  }


} // class CORBAVigenereBreakerPOA
